import Foundation

// MARK: - FactKind

/// Every fact in the Record belongs to exactly one kind.
/// Kind determines: which payload type is valid, which validation rules apply,
/// and how downstream subsystems interpret the fact.
enum FactKind: String, Codable, Sendable, Hashable, CaseIterable {
    case habitLogged
    case reflectionWritten
    case stateCheckedIn
    case correctionSubmitted
    case directionChanged
    case questionAsked
    case permissionChanged
    case calendarEventImported
    case healthSampleImported
    case consentChanged
    case confirmationSubmitted
    case deletionRequested
}

extension FactKind {
    /// Whether this kind represents a user-authored fact (highest authority).
    var isUserAuthored: Bool {
        switch self {
        case .habitLogged, .reflectionWritten, .stateCheckedIn,
             .correctionSubmitted, .directionChanged, .questionAsked,
             .confirmationSubmitted, .deletionRequested:
            return true
        case .permissionChanged, .calendarEventImported,
             .healthSampleImported, .consentChanged:
            return false
        }
    }

    /// Whether this kind's facts may be deduplicated by an external key.
    var supportsSensorDedup: Bool {
        switch self {
        case .calendarEventImported, .healthSampleImported:
            return true
        default:
            return false
        }
    }
}

// MARK: - Fact

/// An immutable, provenance-bearing truth in the Record.
///
/// Invariants (enforced by RecordEngine; never violated by this type):
///  - Once created, a Fact's fields are never mutated.
///  - A Fact's `id` is globally unique within the Record.
///  - A Fact's `provenance` is fully populated — nothing anonymous.
///  - Corrections do not mutate prior Facts; they create new Facts.
///
/// Design: Fact is a value type (struct) so it crosses actor and concurrency
/// boundaries safely. Codable enables persistence and replay.
struct Fact: Sendable, Hashable, Identifiable, Codable {
    /// Globally unique, stable identifier. Never reused, never generated by
    /// the Record itself — the caller provides it so that idempotent retries
    /// present the same ID and the engine deduplicates them.
    let id: UUID

    /// What kind of event this fact records.
    let kind: FactKind

    /// The kind-specific data.
    let payload: FactPayload

    /// Full source attribution. No Fact may exist without provenance.
    let provenance: FactProvenance

    /// When this Fact was durably written to the Record.
    /// Always set by RecordEngine at write time — the caller may not override.
    let recordedAt: Date

    /// When the underlying event occurred.
    /// May predate `recordedAt` for imported/sensor facts (e.g. a step count
    /// sample from three hours ago imported in a background refresh).
    let occurredAt: Date
}

// MARK: - FactDraft

/// A draft fact before it enters the Record.
///
/// FactDraft carries the caller's intent; RecordWriter validates it and
/// transforms it into an immutable Fact. A draft that fails validation
/// never becomes a Fact — it is returned to the caller with a reason.
///
/// The caller supplies the `id` to enable idempotent retries: if the
/// write fails transiently, the same draft (same `id`) can be retried
/// and the engine will deduplicate it.
struct FactDraft: Sendable {
    let id: UUID
    let kind: FactKind
    let payload: FactPayload
    let occurredAt: Date

    // Provenance fields the caller knows.
    // RecordWriter assembles these into a FactProvenance.
    let source: FactSource
    let author: FactAuthor
    let entryMethod: EntryMethod
    let confidence: FactConfidence
    let sourceIdentifier: String?
    let externalTimestamp: Date?

    init(
        id: UUID = UUID(),
        kind: FactKind,
        payload: FactPayload,
        occurredAt: Date = Date(),
        source: FactSource,
        author: FactAuthor,
        entryMethod: EntryMethod,
        confidence: FactConfidence,
        sourceIdentifier: String? = nil,
        externalTimestamp: Date? = nil
    ) {
        self.id = id
        self.kind = kind
        self.payload = payload
        self.occurredAt = occurredAt
        self.source = source
        self.author = author
        self.entryMethod = entryMethod
        self.confidence = confidence
        self.sourceIdentifier = sourceIdentifier
        self.externalTimestamp = externalTimestamp
    }
}

// MARK: - Deduplication key

extension FactDraft {
    /// An opaque deduplication key for sensor/imported facts.
    /// Two drafts with the same key represent the same real-world event —
    /// the second is silently deduplicated (idempotent, not an error).
    ///
    /// Returns nil for user-authored facts, which are deduplicated by `id` only.
    var deduplicationKey: String? {
        guard kind.supportsSensorDedup else { return nil }
        guard let sid = sourceIdentifier else { return nil }
        let ts = (externalTimestamp ?? occurredAt).timeIntervalSince1970
        return "\(kind.rawValue):\(sid):\(ts)"
    }
}

// MARK: - Convenience factories (user-authored facts)

extension FactDraft {

    static func habitLog(
        id: UUID = UUID(),
        habitID: UUID,
        value: Double = 1.0,
        note: String? = nil,
        occurredAt: Date = Date()
    ) -> FactDraft {
        FactDraft(
            id: id,
            kind: .habitLogged,
            payload: .habitLogged(HabitLogPayload(habitID: habitID, value: value, note: note)),
            occurredAt: occurredAt,
            source: .userEntry,
            author: .person,
            entryMethod: .explicit,
            confidence: .known
        )
    }

    static func reflection(
        id: UUID = UUID(),
        text: String,
        promptText: String? = nil,
        seedFactID: UUID? = nil,
        occurredAt: Date = Date()
    ) -> FactDraft {
        FactDraft(
            id: id,
            kind: .reflectionWritten,
            payload: .reflectionWritten(ReflectionPayload(
                text: text,
                promptText: promptText,
                seedFactID: seedFactID
            )),
            occurredAt: occurredAt,
            source: .userEntry,
            author: .person,
            entryMethod: .explicit,
            confidence: .known
        )
    }

    static func stateCheckIn(
        id: UUID = UUID(),
        mood: Int? = nil,
        energy: Int? = nil,
        focus: Int? = nil,
        stress: Int? = nil,
        note: String? = nil,
        occurredAt: Date = Date()
    ) -> FactDraft {
        FactDraft(
            id: id,
            kind: .stateCheckedIn,
            payload: .stateCheckedIn(StateCheckInPayload(
                mood: mood,
                energy: energy,
                focus: focus,
                stress: stress,
                note: note
            )),
            occurredAt: occurredAt,
            source: .userEntry,
            author: .person,
            entryMethod: .explicit,
            confidence: .known
        )
    }

    static func correction(
        id: UUID = UUID(),
        targetFactID: UUID,
        field: String,
        correctedValue: String,
        reason: String? = nil,
        occurredAt: Date = Date()
    ) -> FactDraft {
        FactDraft(
            id: id,
            kind: .correctionSubmitted,
            payload: .correctionSubmitted(CorrectionPayload(
                targetFactID: targetFactID,
                field: field,
                correctedValue: correctedValue,
                reason: reason
            )),
            occurredAt: occurredAt,
            source: .correction,
            author: .person,
            entryMethod: .explicit,
            confidence: .known
        )
    }
}
